# -*- coding: utf-8 -*-

"""
/***************************************************************************
 CHMtoTrees
                                 A QGIS plugin
 Converts a CHM to a vector layer with forest polygons according to various definitions
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2023-05-27
        copyright            : (C) 2023 by Francesco Pirotti - CIRGEO/TESAF University of Padova
        email                : francesco.pirotti@unipd.it
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Francesco Pirotti - CIRGEO/TESAF University of Padova'
__date__ = '2023-05-27'
__copyright__ = '(C) 2023 by Francesco Pirotti - CIRGEO/TESAF University of Padova'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

import math
import shutil

import numpy as np
#import tempfile
from qgis.PyQt.Qt import *
from qgis.PyQt.QtGui import *
from qgis.core import *
from qgis.utils import *
import inspect
import sys
from datetime import datetime
import os
#from qgis.PyQt.QtCore import QCoreApplication
from qgis.core import (QgsProcessing,
                       QgsFeatureSink,
                       QgsProcessingAlgorithm,
                       QgsProcessingParameterFeatureSource,
                       QgsProcessingParameterFileDestination)

dirname, filename = os.path.split(os.path.abspath(__file__))
sys.path.append(dirname)
import cv2 as cv
from osgeo import gdal
import processing
class CHMtoTreesAlgorithm(QgsProcessingAlgorithm):
    """
    This is an example algorithm that takes a vector layer and
    creates a new identical one.

    It is meant to be used as an example of how to create your own
    algorithms and explain methods and variables used to do it. An
    algorithm like this will be available in all elements, and there
    is not need for additional work.

    All Processing algorithms should extend the QgsProcessingAlgorithm
    class.
    """

    # Constants used to refer to parameters and outputs. They will be
    # used when calling the algorithm from another algorithm, or when
    # calling from the QGIS console.

    tmpdir = ''
    OUTPUT = 'OUTPUT'
    INPUT = 'INPUT'
    # PERC_COVER = 'PERC_COVER'
    # MIN_AREA = 'MIN_AREA'
    # MIN_LARGH = 'MIN_LARGH'
    # ALTEZZA_MIN_ALBERO = 'ALTEZZA_MIN_ALBERO'

    def initAlgorithm(self, config):
        """
        Here we define the inputs and output of the algorithm, along
        with some other properties.
        """

        # We add the input vector features source. It can have any kind of
        # geometry.
        self.addParameter(
            QgsProcessingParameterRasterLayer(
                self.INPUT,
                self.tr('Input CHM')
            )
        )
        self.addParameter(QgsProcessingParameterVectorDestination('Aree chiome', 'poligono', type=QgsProcessing.TypeVectorPolygon, createByDefault=True, defaultValue=None))
        self.addParameter(QgsProcessingParameterFeatureSink('Posizione alberi', 'punti', type=QgsProcessing.TypeVectorPoint, createByDefault=True, defaultValue=None))

    def processAlgorithm(self, parameters, context, feedback):
        """
        Here is where the processing itself takes place.
        """
        feedback = QgsProcessingMultiStepFeedback(11, feedback)
        results = {}
        outputs = {}
        start = datetime.now()
        source = self.parameterAsRasterLayer(parameters, self.INPUT, context)
        temppathfile = self.parameterAsFileOutput(parameters, self.OUTPUT, context)

        areaPixel = source.rasterUnitsPerPixelX()*source.rasterUnitsPerPixelX()
        feedback.setProgressText("Preparo il raster in output")
        pipe = QgsRasterPipe()
        sdp = source.dataProvider()
        if source.bandCount() != 1:
            feedback.reportError('Il raster CHM deve avere solamente una banda - il file ' +
                                 str(source.source()) + ' ha ' + str(source.bandCount()) + ' bande!'
                                 )
            return {}

        pipe.set(sdp.clone())

        rasterWriter = QgsRasterFileWriter(temppathfile)
        error = rasterWriter.writeRaster(pipe, sdp.xSize(), sdp.ySize(), sdp.extent(), sdp.crs())

        if error == QgsRasterFileWriter.NoError:
            print("Output preparato con successo!")
        else:
            feedback.reportError('Non sono riuscito ad implementare il raster nuovo OPENING - ' + str(temppathfile))
            return {}

        feedback.setProgressText("Creo il raster temporaneo " + temppathfile+ " di tipo " +  str(source.dataProvider().bandScale(0)))
        tempRasterLayer = QgsRasterLayer(temppathfile)
        provider = tempRasterLayer.dataProvider()
        feedback.setProgressText("reato il raster temporaneo " + provider.name() + " di tipo " +  str(source.dataProvider().bandScale(0)) + " -- - " + str( provider.xSize()) + " x " + str(provider.ySize()))
        block = provider.block(1, provider.extent(), provider.xSize(), provider.ySize())

        if provider is None:
            feedback.reportError('Cannot find or read ' + tempRasterLayer.source())
            return {}

        feedback.setProgressText("Leggo il raster")

        ds = gdal.Open(str(source.source()))
        img =  np.array(ds.GetRasterBand(1).ReadAsArray())
        if img is None:
            feedback.reportError('Errore nella lettura con opencv del CHM ' + source.source())
            return {}

        feedback.setProgressText("Letto raster di dimensioni "+ str(img.shape))


        # Check for cancelation
        if feedback.isCanceled():
            return {}
        feedback.setProgressText("Dimensione immagine: " + ' x '.join(map(str, img.shape)))
        feedback.setProgressText("Applico soglia di altezza di : " +
                                 str(parameters['altezza_alberochioma_m']) + ' metri ')
        # binarize the image
        binr = cv.threshold(img, parameters['altezza_alberochioma_m'], 1, cv.THRESH_BINARY)[1]

        feedback.setProgressText("Processo Invert raster")
        binr = ((binr - 1) * -1).astype('B')

        opening = cv.distanceTransform(binr, cv.DIST_L2, 3)
        #opening[opening == 0] = np.NaN
        provider.setEditable(True)
        data = bytearray(bytes(opening))
        block.setData(data)
        block.setNoDataValue(0)
        writeok = provider.writeBlock(block, 1)
        if writeok:
            feedback.setProgressText("Successo nella scrittura del dato")
        else:
            feedback.setProgressText("Non sono riuscito a scrivere il blocco raster")
            return {}

        provider.setEditable(False)

        out_rlayer = QgsRasterLayer(temppathfile, "Trees")

        mess, success = out_rlayer.loadNamedStyle(dirname+"/extra/style.qml")
        if success is False:
            feedback.setProgressText( mess + " - " + dirname+"/extra/style.qml")
        else:
            feedback.setProgressText( mess)

        QgsProject.instance().addMapLayer(out_rlayer)
        feedback.setProgressText(tempRasterLayer.source())
        stop = datetime.now()
        feedback.setProgressText("Tempo di elaborazione: " + str(stop-start))
        stop = datetime.now()
        return results
    def name(self):
        """
        Returns the algorithm name, used for identifying the algorithm. This
        string should be fixed for the algorithm, and must not be localised.
        The name should be unique within each provider. Names should contain
        lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'CHM => Single Tree Detection'

    def displayName(self):
        """
        Returns the translated algorithm name, which should be used for any
        user-visible display of the algorithm name.
        """
        return self.tr(self.name())

    def group(self):
        """
        Returns the name of the group this algorithm belongs to. This string
        should be localised.
        """
        return self.tr(self.groupId())

    def groupId(self):
        """
        Returns the unique ID of the group this algorithm belongs to. This
        string should be fixed for the algorithm, and must not be localised.
        The group id should be unique within each provider. Group id should
        contain lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return ''

    def tr(self, string):
        return QCoreApplication.translate('Processing', string)

    def createInstance(self):
        return CHMtoTreesAlgorithm()
